INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0135','病案质检情况统计','病案质检情况统计表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0122','临床运行病历书写质量抽查统计表','临床运行病历书写质量抽查统计表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0123','病案文书缺陷统计表','病案文书缺陷统计表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0124','病案文书缺陷统计表','病案文书缺陷统计表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0126','病历质检情况月报表','病历质检情况月报表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0130','迟写病历统计报表','迟写病历统计报表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0117','单病种统计','单病种统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0121','护理缺陷病历统计','护理缺陷病历统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0122','护理文书缺陷统计','护理文书缺陷统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0104','疾病分类统计','疾病分类统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0129','科室病历审签开放报表','科室病历审签开放报表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0127','科室病历质检缺陷情况月报表','科室病历质检缺陷情况月报表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0131','科室迟写病历统计报表','科室迟写病历统计报表','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0107','科室手术例数统计','科室手术例数统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0118','科室医疗质量统计','科室医疗质量统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0119','医师医疗质量统计','医师医疗质量统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0109','抢救病例统计','抢救病例统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0103','全院病历质控率','全院病历质控率','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0101','全院病历质量评价','全院病历质量评价','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0116','日出院明细','日出院明细','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0115','日入院明细','日入院明细','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0105','手术分类统计','手术分类统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0108','死亡病例统计','死亡病例统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0117','单病种统计','单病种统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0104','疾病谱统计','疾病谱统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0118','科室医疗质量统计','科室医疗质量统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0109','抢救病例统计','抢救病例统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0108','死亡病例统计','死亡病例统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0103','全院病历质控率','全院病历质控率','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0120','未按时返回病历统计','未按时返回病历统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0102','医技报告单书写质量监控','医技报告单书写质量监控','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0106','医生手术例数统计','医生手术例数统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

INSERT INTO EMR_REPORT_TEMPLET_INDEX(T_CLASS,T_CODE,T_NAME,FILE_NAME,A_PATH,S_PATH,FORM_TYPE,SYSTEM,FILL_REPLACE,FLAG)
VALUES('AB','AP0122','临床运行病历书写质量抽查统计','临床运行病历书写质量抽查统计','Report\病案统计','Report\病案统计',1,'住院质控',1,0);

