        CREATE SEQUENCE s_CP_PatientExamItem
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_BaseTable
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_PathEnterJudgeCondition
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
    CREATE SEQUENCE s_CP_ExamSyrq
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
    CREATE SEQUENCE s_CP_ExamDictionary
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
    CREATE SEQUENCE s_CP_ExamDictionaryDetail
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
        CREATE SEQUENCE s_CP_AdviceGroupDetail
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
   
   
    CREATE SEQUENCE s_CP_InPatient
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
 
 
   CREATE SEQUENCE s_CP_BedInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
     CREATE SEQUENCE s_CP_TempOrder
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
 
 
  CREATE SEQUENCE s_CP_Longorder
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
        CREATE SEQUENCE s_CP_InPathPatient
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
 
 
  CREATE SEQUENCE s_CP_InPathPatientCondition
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   
CREATE SEQUENCE s_CP_PathExecuteInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   
 CREATE SEQUENCE s_CP_VariationToPath
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_VariantRecords
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
   CREATE SEQUENCE s_CP_AttendanceInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_ClinicalEmrTemplate
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_LogException
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_ClinicalPath_Log
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_QCProblem
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
   CREATE SEQUENCE s_CP_AdviceSuit
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_AdviceSuitDetail
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_DoctorTaskSet
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_PatientContacts
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
   CREATE SEQUENCE s_CP_FamilyHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
  CREATE SEQUENCE s_CP_PersonalHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ; 
  
   CREATE SEQUENCE s_CP_AllergyHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_SurgeryHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_MedicalRecordsHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ; 
  
  
  CREATE SEQUENCE s_CP_IllnessHistory
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ; 
 
 
  CREATE SEQUENCE s_CP_InpatientDiagnosisInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
  CREATE SEQUENCE s_CP_InpathEnterInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
  CREATE SEQUENCE s_CP_InpathExitInfo
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_OrderToPath
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;


 CREATE SEQUENCE s_CP_PathLeadInRecord
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_TriggerConditionDetail
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_TriggerConditionGroup
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_NurExecToPath
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_NurExecRecord
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_MedicalTreatmentWarm
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_NurResult
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_NurExecuteResult
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
         CREATE SEQUENCE s_CP_PathExeActivityChild
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
   CREATE SEQUENCE s_CP_InPatientPathExeDetail
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_PatientEnterConditionRD
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_VitalSignsRecord
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  CREATE SEQUENCE s_CP_PatientInOutRecord
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
  
   CREATE SEQUENCE s_CP_VitalSignSpecialRecord
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
  
   CREATE SEQUENCE s_CP_TreatmentFlow
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
 

    CREATE SEQUENCE s_CP_AdviceGroup
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOORDER
  NOCACHE ;
 